project_id = "wtradfuzjapqkowjpmew"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"
port = 54323

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"
openai_api_key = ""

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[storage]
enabled = true
port = 54328
image_transformation = {enabled = true}
import_map = "deno_dist_dir/import_map.json"

[analytics]
enabled = false
port = 54327
vector_port = 54328

[functions.chatbot-rag]
verify_jwt = false

[functions.twilio-voice-webhook]
verify_jwt = false

[functions.twilio-agent-connect]
verify_jwt = false

[functions.twilio-audio-stream]
verify_jwt = false

[functions.twilio-call-controls]
verify_jwt = false

[functions.twilio-end-call]
verify_jwt = false