// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wtradfuzjapqkowjpmew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0cmFkZnV6amFwcWtvd2pwbWV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNDA3MzAsImV4cCI6MjA3MTcxNjczMH0.qGx23xosw0NhvovbwSNSbclYk5MQ-RQikty87PJk7Mc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});